import type { ComponentType } from "react";
import type { InvitationData, TemplateProps } from "./types";
import type { TemplateWorkflow } from "./workflow";
import { createStandardWorkflow, createMinimalistWorkflow, createLuxuryWorkflow } from "./workflow";
import RoyalMaroon from "./RoyalMaroon";
import EmeraldSouth from "./EmeraldSouth";
import MidnightBlue from "./MidnightBlue";
import GoldenPunjabi from "./GoldenPunjabi";
import RoseGarden from "./RoseGarden";
import TealLuxury from "./TealLuxury";
import IvoryClassic from "./IvoryClassic";
import SaffronFest from "./SaffronFest";
import PearlNikah from "./PearlNikah";
import BlushModern from "./BlushModern";

export interface TemplateMeta {
  id: string;
  name: string;
  tagline: string;
  previewGradient: string;
  religion: ("Hindu" | "Muslim" | "Sikh" | "Christian" | "Jain")[];
  region: ("North" | "South" | "East" | "West" | "Pan-India")[];
  style: ("Traditional" | "Modern" | "Minimal" | "Royal" | "Floral")[];
  colorFamily: ("Red" | "Gold" | "Green" | "Blue" | "Pink" | "Ivory" | "Purple")[];
  isNew: boolean;
  isFeatured: boolean;
  isPremium: boolean;
  isComingSoon: boolean;
  availableOn: ("basic" | "premium" | "elite")[];
  sampleData: {
    brideName: string;
    groomName: string;
    date: string;
    city: string;
  };
  community: string;
  gradient: string;
  motif: string;
}

export interface TemplateRegistryEntry extends TemplateMeta {
  component: ComponentType<TemplateProps>;
  thumbnail_gradient: string;
  description: string;
  tone: string;
  workflow: TemplateWorkflow; // NEW: Workflow config for dynamic steps
}

export type TemplateConfig = TemplateMeta;

export const templates: TemplateMeta[] = [
  {
    id: "royal-maroon",
    name: "Royal Maroon",
    tagline: "A cinematic invitation with video background and golden accents",
    previewGradient: "linear-gradient(160deg,#3A0512 0%,#6B1428 50%,#3A0512 100%)",
    religion: ["Hindu"],
    region: ["North", "Pan-India"],
    style: ["Royal", "Traditional"],
    colorFamily: ["Red", "Gold"],
    isNew: false,
    isFeatured: true,
    isPremium: false,
    isComingSoon: false,
    availableOn: ["basic", "premium", "elite"],
    sampleData: { brideName: "Priya", groomName: "Arjun", date: "15 · 12 · 2026", city: "Jaipur" },
    community: "North Indian",
    gradient: "from-[#7B1C2E] to-[#4a1019]",
    motif: "✦",
  },
  {
    id: "pearl-nikah",
    name: "Pearl Nikah",
    tagline: "Graceful Islamic design with Arabic script support",
    previewGradient: "linear-gradient(160deg,#1a0a16 0%,#3a0e2e 50%,#5C1040 100%)",
    religion: ["Muslim"],
    region: ["South", "North"],
    style: ["Traditional", "Minimal"],
    colorFamily: ["Ivory", "Gold"],
    isNew: true,
    isFeatured: false,
    isPremium: true,
    isComingSoon: true,
    availableOn: ["premium", "elite"],
    sampleData: { brideName: "Aisha", groomName: "Zayan", date: "05 · 12 · 2026", city: "Hyderabad" },
    community: "Muslim",
    gradient: "from-stone-600 to-stone-800",
    motif: "◆",
  },
  {
    id: "golden-sehra",
    name: "Golden Sehra",
    tagline: "Vibrant Punjabi design with Gurmukhi script support",
    previewGradient: "linear-gradient(160deg,#2A1800,#6B4000,#2A1800)",
    religion: ["Sikh"],
    region: ["North"],
    style: ["Traditional", "Royal"],
    colorFamily: ["Gold", "Red"],
    isNew: true,
    isFeatured: false,
    isPremium: false,
    isComingSoon: true,
    availableOn: ["premium", "elite"],
    sampleData: { brideName: "Simran", groomName: "Harjeet", date: "22 · 11 · 2026", city: "Amritsar" },
    community: "Sikh",
    gradient: "from-amber-600 to-orange-800",
    motif: "☬",
  },
  {
    id: "midnight-blue",
    name: "Midnight Blue",
    tagline: "Elegant destination wedding design for the modern couple",
    previewGradient: "linear-gradient(160deg,#0a0d1a,#0e1a3a,#1c2d6b)",
    religion: ["Hindu", "Christian"],
    region: ["Pan-India"],
    style: ["Modern", "Minimal"],
    colorFamily: ["Blue", "Gold"],
    isNew: true,
    isFeatured: false,
    isPremium: false,
    isComingSoon: true,
    availableOn: ["basic", "premium", "elite"],
    sampleData: { brideName: "Meera", groomName: "Vivek", date: "10 · 04 · 2026", city: "Mumbai" },
    community: "Modern",
    gradient: "from-slate-800 to-slate-950",
    motif: "◇",
  },
  {
    id: "emerald-south",
    name: "Emerald South",
    tagline: "Elegant South Indian design with botanical accents",
    previewGradient: "linear-gradient(160deg,#0D2818 0%,#1A5C30 60%,#0D2818 100%)",
    religion: ["Hindu"],
    region: ["South"],
    style: ["Traditional", "Floral"],
    colorFamily: ["Green", "Gold"],
    isNew: true,
    isFeatured: false,
    isPremium: false,
    isComingSoon: true,
    availableOn: ["premium", "elite"],
    sampleData: { brideName: "Kavya", groomName: "Siddharth", date: "20 · 04 · 2026", city: "Bangalore" },
    community: "South Indian",
    gradient: "from-emerald-800 to-emerald-950",
    motif: "❂",
  },
  {
    id: "teal-luxury",
    name: "Marigold Mandap",
    tagline: "Regal Maharashtrian design with Sanskrit verse support",
    previewGradient: "linear-gradient(160deg,#0E0600 0%,#7A4008 45%,#B86010 65%,#180800 100%)",
    religion: ["Hindu"],
    region: ["West"],
    style: ["Royal", "Traditional"],
    colorFamily: ["Gold", "Red"],
    isNew: false,
    isFeatured: false,
    isPremium: true,
    isComingSoon: true,
    availableOn: ["elite"],
    sampleData: { brideName: "Kavya", groomName: "Siddharth", date: "Vivah Sohala", city: "Pune" },
    community: "Marathi",
    gradient: "from-amber-700 to-orange-950",
    motif: "🌼",
  },
  {
    id: "rose-garden",
    name: "Rose Garden",
    tagline: "Romantic floral design with soft pastel tones",
    previewGradient: "linear-gradient(160deg,#4c0519 0%,#9f1239 50%,#4c0519 100%)",
    religion: ["Hindu", "Christian", "Jain"],
    region: ["Pan-India"],
    style: ["Floral", "Modern"],
    colorFamily: ["Pink", "Gold"],
    isNew: true,
    isFeatured: false,
    isPremium: false,
    isComingSoon: true,
    availableOn: ["basic", "premium", "elite"],
    sampleData: { brideName: "Ananya", groomName: "Rohan", date: "25 · 02 · 2026", city: "Delhi" },
    community: "Muslim",
    gradient: "from-rose-700 to-pink-900",
    motif: "✿",
  },
  {
    id: "chapel-white",
    name: "Chapel White",
    tagline: "Clean, elegant design for Christian weddings",
    previewGradient: "linear-gradient(160deg,#f5f0e8 0%,#e8dfd2 50%,#f5f0e8 100%)",
    religion: ["Christian"],
    region: ["South", "West"],
    style: ["Minimal", "Modern"],
    colorFamily: ["Ivory", "Gold"],
    isNew: true,
    isFeatured: false,
    isPremium: false,
    isComingSoon: true,
    availableOn: ["basic", "premium", "elite"],
    sampleData: { brideName: "Maria", groomName: "Samuel", date: "14 · 02 · 2026", city: "Goa" },
    community: "Christian",
    gradient: "from-stone-200 to-stone-400",
    motif: "✝",
  },
];

export const TEMPLATE_REGISTRY: Record<string, TemplateRegistryEntry> = {
  "royal-maroon": {
    id: "royal-maroon",
    name: "Royal Maroon",
    component: RoyalMaroon,
    community: "North Indian",
    tone: "Traditional",
    description: "Rich maroons and gold with mandala motifs",
    thumbnail_gradient: "linear-gradient(135deg, #3A0512, #7B1C2E)",
    previewGradient: "linear-gradient(160deg,#3A0512 0%,#6B1428 50%,#3A0512 100%)",
    tagline: "A cinematic invitation with video background and golden accents",
    religion: ["Hindu"],
    region: ["North", "Pan-India"],
    style: ["Royal", "Traditional"],
    colorFamily: ["Red", "Gold"],
    isNew: false,
    isFeatured: true,
    isPremium: false,
    workflow: createStandardWorkflow("royal-maroon"),
    isComingSoon: false,
    availableOn: ["basic", "premium", "elite"],
    sampleData: { brideName: "Priya", groomName: "Arjun", date: "15 · 12 · 2026", city: "Jaipur" },
    gradient: "from-[#7B1C2E] to-[#4a1019]",
    motif: "✦",
  },
  "emerald-south": {
    id: "emerald-south",
    name: "Emerald South",
    component: EmeraldSouth,
    community: "South Indian",
    tone: "Elegant",
    description: "Jewel tones with temple motifs",
    thumbnail_gradient: "linear-gradient(135deg, #0d2818, #1a5c30)",
    previewGradient: "linear-gradient(160deg,#0D2818 0%,#1A5C30 60%,#0D2818 100%)",
    tagline: "Elegant South Indian design with botanical accents",
    religion: ["Hindu"],
    region: ["South"],
    style: ["Traditional", "Floral"],
    colorFamily: ["Green", "Gold"],
    isNew: true,
    isFeatured: false,
    isPremium: false,
    isComingSoon: true,
    availableOn: ["premium", "elite"],
    sampleData: { brideName: "Kavya", groomName: "Siddharth", date: "20 · 04 · 2026", city: "Bangalore" },
    gradient: "from-emerald-800 to-emerald-950",
    motif: "❂",
  },
  "midnight-blue": {
    id: "midnight-blue",
    name: "Midnight Blue",
    component: MidnightBlue,
    community: "Modern",
    tone: "Minimal",
    description: "Sleek slate blues with diamond accents",
    thumbnail_gradient: "linear-gradient(135deg, #1e293b, #0f172a)",
    previewGradient: "linear-gradient(160deg,#0a0d1a,#0e1a3a,#1c2d6b)",
    tagline: "Elegant destination wedding design for the modern couple",
    religion: ["Hindu", "Christian"],
    region: ["Pan-India"],
    style: ["Modern", "Minimal"],
    colorFamily: ["Blue", "Gold"],
    isNew: true,
    isFeatured: false,
    isPremium: false,
    isComingSoon: true,
    availableOn: ["basic", "premium", "elite"],
    sampleData: { brideName: "Meera", groomName: "Vivek", date: "10 · 04 · 2026", city: "Mumbai" },
    gradient: "from-slate-800 to-slate-950",
    motif: "◇",
  },
  "golden-punjabi": {
    id: "golden-punjabi",
    name: "Golden Punjabi",
    component: GoldenPunjabi,
    community: "Sikh",
    tone: "Traditional",
    description: "Warm gold with Khanda motifs",
    thumbnail_gradient: "linear-gradient(135deg, #3d2800, #8B6914)",
    previewGradient: "linear-gradient(160deg,#2A1800,#6B4000,#2A1800)",
    tagline: "Vibrant Punjabi design with Gurmukhi script support",
    religion: ["Sikh"],
    region: ["North"],
    style: ["Traditional", "Royal"],
    colorFamily: ["Gold", "Red"],
    isNew: true,
    isFeatured: false,
    isPremium: true,
    isComingSoon: false,
    availableOn: ["premium", "elite"],
    sampleData: { brideName: "Simran", groomName: "Harjeet", date: "22 · 11 · 2026", city: "Amritsar" },
    gradient: "from-amber-600 to-orange-800",
    motif: "☬",
  },
  "rose-garden": {
    id: "rose-garden",
    name: "Rose Garden",
    component: RoseGarden,
    community: "Muslim",
    tone: "Floral",
    description: "Soft rose and pink with floral patterns",
    thumbnail_gradient: "linear-gradient(135deg, #4c0519, #9f1239)",
    previewGradient: "linear-gradient(160deg,#4c0519 0%,#9f1239 50%,#4c0519 100%)",
    tagline: "Romantic floral design with soft pastel tones",
    religion: ["Hindu", "Christian", "Jain"],
    region: ["Pan-India"],
    style: ["Floral", "Modern"],
    colorFamily: ["Pink", "Gold"],
    isNew: true,
    isFeatured: false,
    isPremium: false,
    isComingSoon: true,
    availableOn: ["basic", "premium", "elite"],
    sampleData: { brideName: "Ananya", groomName: "Rohan", date: "25 · 02 · 2026", city: "Delhi" },
    gradient: "from-rose-700 to-pink-900",
    motif: "✿",
  },
  "teal-luxury": {
    id: "teal-luxury",
    name: "Marigold Mandap",
    component: TealLuxury,
    community: "Marathi",
    tone: "Luxury",
    description: "Warm marigold and saffron with mandap motifs",
    thumbnail_gradient: "linear-gradient(135deg, #3A1A00, #B86010)",
    previewGradient: "linear-gradient(160deg,#0E0600 0%,#7A4008 45%,#B86010 65%,#180800 100%)",
    tagline: "Regal Maharashtrian design with Sanskrit verse support",
    religion: ["Hindu"],
    region: ["West"],
    style: ["Royal", "Traditional"],
    colorFamily: ["Gold", "Red"],
    isNew: false,
    isFeatured: false,
    isPremium: true,
    isComingSoon: true,
    availableOn: ["elite"],
    sampleData: { brideName: "Kavya", groomName: "Siddharth", date: "Vivah Sohala", city: "Pune" },
    gradient: "from-amber-700 to-orange-950",
    motif: "🌼",
  },
  "ivory-classic": {
    id: "ivory-classic",
    name: "Ivory Classic",
    component: IvoryClassic,
    community: "North Indian",
    tone: "Luxury",
    description: "Warm ivory and gold in a classic design",
    thumbnail_gradient: "linear-gradient(135deg, #3a2e1a, #5c4a2f)",
    previewGradient: "linear-gradient(160deg,#f5f0e8 0%,#e8dfd2 50%,#f5f0e8 100%)",
    tagline: "Clean, elegant design for Christian weddings",
    religion: ["Hindu"],
    region: ["North", "Pan-India"],
    style: ["Traditional", "Royal"],
    colorFamily: ["Ivory", "Gold"],
    isNew: true,
    isFeatured: false,
    isPremium: true,
    isComingSoon: false,
    availableOn: ["premium", "elite"],
    sampleData: { brideName: "Maria", groomName: "Samuel", date: "14 · 02 · 2026", city: "Goa" },
    gradient: "from-stone-200 to-stone-400",
    motif: "✝",
  },
  "saffron-fest": {
    id: "saffron-fest",
    name: "Saffron Fest",
    component: SaffronFest,
    community: "North Indian",
    tone: "Playful",
    description: "Vibrant saffron and red, full of energy",
    thumbnail_gradient: "linear-gradient(135deg, #9a3412, #ea580c)",
    previewGradient: "linear-gradient(160deg,#9A3412 0%,#EA580C 50%,#9A3412 100%)",
    tagline: "Regal Maharashtrian design with Sanskrit verse support",
    religion: ["Hindu"],
    region: ["West"],
    style: ["Royal", "Traditional"],
    colorFamily: ["Gold", "Red"],
    isNew: false,
    isFeatured: false,
    isPremium: true,
    isComingSoon: false,
    availableOn: ["elite"],
    sampleData: { brideName: "Kavya", groomName: "Siddharth", date: "Vivah Sohala", city: "Pune" },
    gradient: "from-amber-700 to-orange-950",
    motif: "🌼",
  },
  "blush-modern": {
    id: "blush-modern",
    name: "Blush Modern",
    component: BlushModern,
    community: "Modern",
    tone: "Minimal",
    description: "Contemporary blush pink and fuchsia",
    thumbnail_gradient: "linear-gradient(135deg, #a21caf, #f472b6)",
    previewGradient: "linear-gradient(160deg,#f5f0e8 0%,#e8dfd2 50%,#f5f0e8 100%)",
    tagline: "Contemporary blush pink and fuchsia",
    religion: ["Hindu"],
    region: ["Pan-India"],
    style: ["Modern", "Minimal"],
    colorFamily: ["Pink", "Purple"],
    isNew: false,
    isFeatured: false,
    isPremium: false,
    isComingSoon: false,
    availableOn: ["basic", "premium", "elite"],
    sampleData: { brideName: "Ananya", groomName: "Rohan", date: "25 · 02 · 2026", city: "Delhi" },
    gradient: "from-pink-500 to-fuchsia-700",
    motif: "✿",
  },
};

export const TEMPLATE_ID_LIST = templates.map((t) => t.id) as string[];

export const getTemplateById = (id: string) => templates.find((t) => t.id === id);
export const getTemplateConfigById = (id: string) => templates.find((t) => t.id === id);

export const FILTER_OPTIONS = {
  religion: ["Hindu", "Muslim", "Sikh", "Christian", "Jain"] as const,
  region: ["North", "South", "East", "West", "Pan-India"] as const,
  style: ["Traditional", "Modern", "Minimal", "Royal", "Floral"] as const,
  colorFamily: [
    { label: "Red", dot: "#dc2626" },
    { label: "Gold", dot: "#d97706" },
    { label: "Green", dot: "#16a34a" },
    { label: "Blue", dot: "#2563eb" },
    { label: "Pink", dot: "#ec4899" },
    { label: "Ivory", dot: "#e8dfd2" },
    { label: "Purple", dot: "#9333ea" },
  ] as const,
  badge: ["Featured", "New", "Premium"] as const,
};

export type TemplateId = keyof typeof TEMPLATE_REGISTRY;

export const DEMO_DATA: InvitationData = {
  bride_name: "Ananya",
  groom_name: "Rohan",
  bride_family: "Daughter of Shri Ramesh & Smt. Sunita Sharma, New Delhi",
  groom_family: "Son of Shri Vijay & Smt. Meena Kapoor, Mumbai",
  personal_message: "Together with our families, we joyfully invite you to celebrate our wedding.",
  our_story: "We met on a rainy evening in Delhi, and from that very first cup of chai together, we knew something beautiful had begun.",
  wedding_date: "2025-11-15",
  language: "english",
  gallery_photos: [],
  dresscode_enabled: false,
  dresscode_text: "",
  dresscode_colors: [],
  music_url: "",
  events: [
    { event_type: "mehndi", event_name: "Mehndi", event_date: "2025-11-13", event_time: "16:00", venue_name: "Sharma Residence", venue_address: "Vasant Kunj, New Delhi", maps_url: "", is_enabled: true },
    { event_type: "haldi", event_name: "Haldi", event_date: "2025-11-14", event_time: "10:00", venue_name: "Sharma Residence", venue_address: "Vasant Kunj, New Delhi", maps_url: "", is_enabled: true },
    { event_type: "sangeet", event_name: "Sangeet", event_date: "2025-11-14", event_time: "19:00", venue_name: "The Grand Ballroom", venue_address: "The Leela Palace, New Delhi", maps_url: "", is_enabled: true },
    { event_type: "ceremony", event_name: "Vivah", event_date: "2025-11-15", event_time: "21:00", venue_name: "The Leela Palace", venue_address: "Chanakyapuri, New Delhi", maps_url: "", is_enabled: true },
    { event_type: "reception", event_name: "Reception", event_date: "2025-11-16", event_time: "19:00", venue_name: "The Leela Palace", venue_address: "Chanakyapuri, New Delhi", maps_url: "", is_enabled: true },
  ],
};

export const DEMO_CONFIG = {
  couple: {
    brideName: "Ananya",
    groomName: "Rohan",
    brideFamily: "Daughter of Shri Ramesh & Smt. Sunita Sharma, New Delhi",
    groomFamily: "Son of Shri Vijay & Smt. Meena Kapoor, Mumbai",
    story: "We met on a rainy evening in Delhi, and from that very first cup of chai together, we knew something beautiful had begun.",
  },
  weddingDate: "2025-11-15",
  personalMessage: "Together with our families, we joyfully invite you to celebrate our wedding.",
  language: "english",
  events: [
    { type: "mehndi", name: "Mehndi", date: "2025-11-13", time: "16:00", venueName: "Sharma Residence", venueAddress: "Vasant Kunj, New Delhi" },
    { type: "haldi", name: "Haldi", date: "2025-11-14", time: "10:00", venueName: "Sharma Residence", venueAddress: "Vasant Kunj, New Delhi" },
    { type: "sangeet", name: "Sangeet", date: "2025-11-14", time: "19:00", venueName: "The Grand Ballroom", venueAddress: "The Leela Palace, New Delhi" },
    { type: "ceremony", name: "Vivah", date: "2025-11-15", time: "21:00", venueName: "The Leela Palace", venueAddress: "Chanakyapuri, New Delhi" },
    { type: "reception", name: "Reception", date: "2025-11-16", time: "19:00", venueName: "The Leela Palace", venueAddress: "Chanakyapuri, New Delhi" },
  ],
};
